stages:
  - build

variables:
  DOCKER_REGISTRY: ghcr.io
  GITHUB_USERNAME: rbourgeat
  GITHUB_TOKEN: $CI_JOB_TOKEN

build:
  stage: build
  image: docker:20.10.7

  services:
    - docker:dind

  before_script:
    - echo $GITHUB_TOKEN | docker login $DOCKER_REGISTRY -u $GITHUB_USERNAME --password-stdin

  script:
    - docker build -t $DOCKER_REGISTRY/$GITHUB_USERNAME/$CI_PROJECT_NAME:latest .
    - docker push $DOCKER_REGISTRY/$GITHUB_USERNAME/$CI_PROJECT_NAME:latest

  only:
    - main
